CREATE TABLE Users(
                      id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                      username varchar(100) NOT NULL,
                      password varchar NOT NULL
);

INSERT INTO Users (username, "password") VALUES ('user1', 'password1');
INSERT INTO Users (username, "password") VALUES ('user2', 'password2');
